# audio_profiles.py
"""Per-model audio processing configuration profiles for music generation."""

PROFILES = {
    "ace_step_v15": {
        "sample_rate": 48000,
        "lufs": -14.0,
        "clipping": 0.95,
        "denoise_strength": 0.2,
        "highpass_cutoff": 30,
        "stereo_width": 1.2,
        "eq_preset": "balanced",
        "compression_ratio": 2.0,
        "trim_db": -45,
        "min_silence_ms": 500,
        "front_protect_ms": 200,
        "end_protect_ms": 1000,
    },
    "ace_step_v1": {
        "sample_rate": 48000,
        "lufs": -14.0,
        "clipping": 0.95,
        "denoise_strength": 0.2,
        "highpass_cutoff": 30,
        "stereo_width": 1.2,
        "eq_preset": "balanced",
        "compression_ratio": 2.0,
        "trim_db": -45,
        "min_silence_ms": 500,
        "front_protect_ms": 200,
        "end_protect_ms": 1000,
    },
    "heartmula": {
        "sample_rate": 48000,
        "lufs": -14.0,
        "clipping": 0.95,
        "denoise_strength": 0.15,
        "highpass_cutoff": 30,
        "stereo_width": 1.1,
        "eq_preset": "balanced",
        "compression_ratio": 2.0,
        "trim_db": -45,
        "min_silence_ms": 500,
        "front_protect_ms": 200,
        "end_protect_ms": 1000,
    },
    "diffrhythm": {
        "sample_rate": 44100,
        "lufs": -14.0,
        "clipping": 0.95,
        "denoise_strength": 0.2,
        "highpass_cutoff": 30,
        "stereo_width": 1.2,
        "eq_preset": "balanced",
        "compression_ratio": 2.0,
        "trim_db": -45,
        "min_silence_ms": 500,
        "front_protect_ms": 200,
        "end_protect_ms": 1000,
    },
    "yue": {
        "sample_rate": 44100,
        "lufs": -14.0,
        "clipping": 0.95,
        "denoise_strength": 0.25,
        "highpass_cutoff": 30,
        "stereo_width": 1.0,
        "eq_preset": "balanced",
        "compression_ratio": 2.0,
        "trim_db": -45,
        "min_silence_ms": 500,
        "front_protect_ms": 200,
        "end_protect_ms": 1000,
    },
    "musicgen": {
        "sample_rate": 32000,
        "lufs": -14.0,
        "clipping": 0.95,
        "denoise_strength": 0.15,
        "highpass_cutoff": 30,
        "stereo_width": 1.0,
        "eq_preset": "balanced",
        "compression_ratio": 2.0,
        "trim_db": -45,
        "min_silence_ms": 500,
        "front_protect_ms": 200,
        "end_protect_ms": 1000,
    },
    "riffusion": {
        "sample_rate": 44100,
        "lufs": -14.0,
        "clipping": 0.95,
        "denoise_strength": 0.3,
        "highpass_cutoff": 30,
        "stereo_width": 1.2,
        "eq_preset": "warm",
        "compression_ratio": 2.0,
        "trim_db": -45,
        "min_silence_ms": 500,
        "front_protect_ms": 200,
        "end_protect_ms": 1000,
    },
    "stable_audio": {
        "sample_rate": 44100,
        "lufs": -14.0,
        "clipping": 0.95,
        "denoise_strength": 0.2,
        "highpass_cutoff": 30,
        "stereo_width": 1.2,
        "eq_preset": "balanced",
        "compression_ratio": 2.0,
        "trim_db": -45,
        "min_silence_ms": 500,
        "front_protect_ms": 200,
        "end_protect_ms": 1000,
    },
}

# EQ presets: (low_shelf_db, mid_notch_db, high_shelf_db)
EQ_PRESETS = {
    "flat": (0.0, 0.0, 0.0),
    "balanced": (1.5, -1.0, 1.0),
    "warm": (3.0, -1.5, -0.5),
    "bright": (0.0, -0.5, 2.5),
}
